Add playbook for testing upgrades on Azure
oamg/snippets pull request #5
Opened 2020-09-03 14:22 UTC by Rezney

2020-09-04 12:22 UTC, pirat89 commented on playbooks/azure/leapp-rhui-azure.spec
> +%global leappfilespath  usr/share/leapp-repository/repositories/system_upgrade/el7toel8/files/rhui
Not real blocker in snippet repos, but bett could be use of `%{_datadir}` macro instead of `usr/share`

```suggestion
%global leappfilespath  %{_datadir}/leapp-repository/repositories/system_upgrade/el7toel8/files/rhui
```

Paths in the rest of SPEC file has to corrected in such a case as the macro starts with the slash `/usr/share`.

2020-09-10 12:52 UTC, Rezney commented
@pirat89 could you please check now?

2020-09-10 13:09 UTC, pirat89 requested changes

2020-09-10 13:09 UTC, pirat89 commented on playbooks/azure/leapp-rhui-azure.spec
> +mkdir -p %{buildroot}/%{leappfilespath}/%{provider}
@mreznik remove the slash before the macro everywhere, so the result is not `/<buildroot>//usr/...`, but `/<buildroot>/usr/...`

e.g.
```suggestion
mkdir -p %{buildroot}%{leappfilespath}/%{provider}
```

2020-09-10 17:40 UTC, Rezney commented on playbooks/azure/leapp-rhui-azure.spec
> +mkdir -p %{buildroot}/%{leappfilespath}/%{provider}
like you did not tell before. Got it now...

2020-09-11 15:02 UTC, pirat89 approved these changes
lgtm

2020-09-11 15:04 UTC, pirat89 approved these changes

2020-09-11 15:04 UTC, merged